### ISSUE TITLE
Revise sort order of Lemmy Instances on https://join-lemmy.org/instances

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/joinlemmy-site#110]
This is sort of a which came first question - the chicken or the egg?

What comes first - the users or the content?

Once of the nice things about federated systems like Lemmy is users on other instances can participate in your communities. So the attractiveness of the instance should really be measured by the number of users in a community regardless if they signed up on your instance or not.

At the moment, based on the sort order on https://join-lemmy.org/instances some instances are ranking higher in terms of "users per month" but when you look at the commmunities list for that instance the number of users per month can be a lot higher of lower.

My suggestion is to base the sort order on the number of users per month for the highest ranking community on that instance. That way people interested in joining will see the instances with the most engaging content/communities. At the end of the day - getting them engaged in the content/community is going to grow long term users.

**Comment by dessalines** [comment]
There are some recommended instances, and then below that is the popular section, which is already sorted by users per month.

**Comment by dessalines** [comment]
Another possibility: you actually do only have 2 active *local* users, and the community activity is from federated users.

**Comment by Kap2022** [comment]
Is there a good reason why federated users would be worth less then local users?

In a way federated users are more valuable because they show the federation concept is working.

**Comment by dessalines** [comment]
That would double count a lot of posts and comments that exist on tons of instances. The current site activity queries are limited to local users only.
