### ISSUE TITLE
Allow instances to opt-out from join-lemmy.org/instances

### ISSUE THREAD

**Issue by ColdHotman** [LemmyNet/joinlemmy-site#117]
My home instance doesn't advertise and in 99.9% of cases interact exclusively within the lemmyverse. The majority of membership applicants does not read the sidebar and doesn't give the impression they know what the instance is about. On top of that there's a surprising amount of garbage applications.

The only place we know that externally advertise our presence is join-lemmy.org/instances.

We'd like the possibility to opt-out to the directory on join-lemmy.org until we have the infrastructure and volunteers to handle this situation.

**Comment by dessalines** [comment]
@Nutomic add them to the do not scan list for your instance building script if you would. 

Also you can close registrations if you don't want to take on new users. But if your site is linked anywhere else, search engines will crawl it.

**Comment by Nutomic** [comment]
You can make a PR to add your instance in [this line](https://github.com/LemmyNet/joinlemmy-site/blob/main/recommended-instances.json#L9). Once merged, your instance will automatically be excluded from the list.

**Comment by dessalines** [comment]
Watch a video or read an article on how to make a pull request on github. @Nutomic linked you the repo and line that needs changing.

**Comment by dessalines** [comment]
I'll keep this in mind when you want us to do free labor for you, with all your other requests as well.

**Comment by Nutomic** [comment]
Fixed in https://github.com/LemmyNet/joinlemmy-site/pull/118
