### ISSUE TITLE
Federated users per month

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/joinlemmy-site#122]
The instance list currently only shows the number of local active users per instance. This can give the false impressions that small instances are almost dead. It would be good if we could also show the number of federated active users which can be seen from that instance. This can be especially useful to make small instances look more active.

I [implemented this functionality in lemmy-stats-crawler](https://git.join-lemmy.org/LemmyNet/lemmy-stats-crawler/pulls/12). Now it just needs to be added on the site, probably below the existing (local) number of active users per instance.

**Comment by Nutomic** [comment]
Fully agree. Thats why I would show it underneath the current number of (local) users per month, but not sure how to get that working in html/css.

**Comment by dessalines** [comment]
The new site has a lemmyverse total active user count at the top of its join page now, that probably serves this.
