### ISSUE TITLE
Better API documentation

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/joinlemmy-site#13]
[We currently have this](https://dev.lemmy.ml/docs/contributing_websocket_http_api.html), but afaik thats written by hand and not fully up to date. It would be nice if we could auto-generate better API docs in some way, because a lot of people want to write clients right now. This would also make it easier to keep up to date with future changes.

**Comment by dessalines** [comment]
The final step before we close this, is :

- @gazconroy finishing up the asyncapi
- Moving all the API documentation into it, including the other comments
- Deleting the old api doc

**Comment by dessalines** [comment]
This is converted over now.
