### ISSUE TITLE
Request to re-add exploding-heads.com to the instance list

### ISSUE THREAD

**Issue by Aviator7290** [LemmyNet/joinlemmy-site#154]
Hello,

I am one of the users of this instance and I am pretty sad to see that it is removed from the list. With the current Reddit API situation a lot of people are running away from it and would like to join the fediverse. There are also people who would like to not be a part of left instance for their own reasons. Sadly, people aren't given the opportunity to join non left leaning instance. 

Thanks in advance!

**Comment by dessalines** [comment]
Not in

**Comment by Nutomic** [comment]
The instance list is build automatically using [lemmy-stats-crawler](https://github.com/LemmyNet/lemmy-stats-crawler). The crawler only includes instances running Lemmy 0.17+, so your instance will be included again once it is updated.
