### ISSUE TITLE
Add short explanation to instances list

### ISSUE THREAD

**Issue by aerkiaga** [LemmyNet/joinlemmy-site#155]
Currently, the instances list begins with the following sentence:

> The lemmyverse currently has 95 instances, and 2.6K monthly active users.

Then, a list of instances is presented to the user. However, if a user comes to this page by simply clicking the button in the main page after having clicked a link in some other site, it's likely they'll not know what the _lemmyverse_ is, i.e. that instances can communicate with each other, so they might assume that they should simply join the most popular one, lemmy.ml, in order to have access to the most content.

Since this particular page presents the user with a choice, it's the perfect place to put a short explanation to guide them. And since the sentence above talks about the _lemmyverse_, it's appropriate to add this explanation right before it. Candidates might include:

* "From any server, you can see all the posts and comments in other servers."
* "The lemmyverse is made up of many servers, all of which can see each other's content."
* "No matter what server you sign up to, you'll be able to see all content in the lemmyverse."

I personally prefer the third one, as it both explains what the _lemmyverse_ is and clearly relates this information to the choice at hand.

I would have added the explanation myself, but to be honest I've never done web dev in my life and this code looks so foreign to me that I can't even figure out how to make this small change :)

**Comment by Nutomic** [comment]
The code is in this file: https://github.com/LemmyNet/joinlemmy-site/blob/main/src/shared/components/instances.tsx

It might be enough if you change the relevant translation string here: https://github.com/LemmyNet/joinlemmy-translations/blob/main/translations/en.json
