### ISSUE TITLE
Table Comparison for Lemmy Instances

### ISSUE THREAD

**Issue by maltfield** [LemmyNet/joinlemmy-site#157]
This ticket is a request to add a data table to the join-lemmy.org website that provides useful data points for each of the Lemmy Servers.

First of all, thank you for your work on Lemmy. I only discovered it today on reddit. Like many reddit users, I am looking for an alternative due to the upcoming API changes that will very likely make all open-source reddit clients inoperable. I was very glad to find lemmy!

# Why?

Unfortunately, I spent a few hours trying to find the appropriate instance. I created accounts on several instances, but after I registered, I discovered that on some instances:

1. I shouldn't use some instances because the mods are saying the increased load is causing issues (eg lemmy.ml)
1. I created an account but I couldn't use my account immediately (eg moero.house)
2. The moderator has appeared to block some other instances with an enormous amount of content & communities, but didn't say why (lemmy.one, slrpnk.net)
3. Some instances appear to be blocked by a lot of other instances, with no apparent explanation for why (lemmygrad.ml)
4. Some instances disable very important features like downvotes (blahaj)

It's great that federation gives server instance admins the ability to customize how their instance works.

**It's bad that new users can't easily see all of these details when they're trying to pick an instance** to signup for.

# Suggested Fields in Data Table

To solve this issue, I think join-lemmy.org should add a (sortable) data table that makes it very easy to see this information at-a-glance. I'd recommend starting with the following fields:

1. Sever **Uptime** (a percent between 0-100)
2. **Account Creation Difficulty** (low = can create an account and use it immediately, medium = account usable in less than one hour after creation, high = needs to wait more than one hour to use account)
3. **Downvotes** (enabled, disabled)
4. **Adult** Friendly (yes = allows cussing/nudity/etc, no = blocks adult content)
5. **Community Creation** (yes = normal users can create communities, no = only admins can create new communities)
6. **Federation State** (open, blocklist, allowlist)
7. **Block List** (none = no instances blocked by this instance, some = a few instances blocked by this instance, many = a lot of instances are blocked by this instance)
8. **Blocked By** (none = no other instances block this instance, some = a few other instances block this instance, many = a lot of other instances block this instance)
9. **Host Country** (ISO country code)
10.  **Green Hosting** ([yes](https://joinfediverse.wiki/index.php?title=GreenFediverse), no)

**Comment by Nutomic** [comment]
Contributions welcome. You can also create your own website which provides this information, using [lemmy-stats-crawler](https://github.com/LemmyNet/lemmy-stats-crawler/).

**Comment by maltfield** [comment]
@Nutomic thanks for the fast response!

> Contributions welcome

that's a lot of work. Before anyone invests in contributing this feature, can you say if:

1. you are the sole maintainer of join-lemmy.org and
2. you would merge this feature into this repo?

**Comment by Nutomic** [comment]
All projects in this org are maintained by @dessalines and me. We will generally merge anything that passes ci and makes the project better. And improving the instance list would definitely be good. So any work in this area is more than welcome!

**Comment by maltfield** [comment]
See also "Is it possible to query a lemmy instance’s Federation State?"

 * https://lemmy.ml/post/1161575

**Comment by dessalines** [comment]
The nodeinfo has federation status iirc.

**Comment by maltfield** [comment]
not sure if I'm doing this right (I've never heard of nodeinfo before, but I googled it and am making some guesses)

```
user@host:~$ curl https://lemmy.ml/.well-known/nodeinfo
{"links":[{"rel":"http://nodeinfo.diaspora.software/ns/schema/2.0","href":"https://lemmy.ml/nodeinfo/2.0.json"}]}user@host:~$ 
user@host:~$ 
user@host:~$ curl https://lemmy.ml/nodeinfo/2.0.json
{"version":"2.0","software":{"name":"lemmy","version":"0.17.3"},"protocols":["activitypub"],"usage":{"users":{"total":31036,"activeHalfyear":1974,"activeMonth":1390},"localPosts":76604,"localComments":148411},"openRegistrations":false}user@host:~$ 
```

**Comment by maltfield** [comment]
@Nutomic can you please enable issues on this repo?

 * https://github.com/LemmyNet/lemmy-stats-crawler

I wanted to report an error when attempting to run the `cargo` command in the README, but it's not possible to create an issue on that repo.

**Comment by dessalines** [comment]
@maltfield I spose I'm not sure what you mean by federation state. 

The nodeinfo has `openRegistrations` boolean in its response there.

The site endpoint *currently* has a list of allowed and blocked instances. 
https://lemmy.ml/api/v3/site 

In the next release, that endpoint will be `/federated_instances`

**Comment by Nutomic** [comment]
Enabled issues for lemmy-stats-crawler.

Regarding "federation state": You can have a blocklist, then Lemmy will federate with every instance except blocked ones. Or have an allowlist, then it will only federate with the allowed ones. If neither is set then it also federate with everything. Using allowlist and blocklist together doesnt make much sense, then it would only federate with allowed instances which are not in the blocklist. 

The docs could use an update, pull request welcome (in lemmy-docs repo).

**Comment by maltfield** [comment]
It appears that the relevant sourcecode that generates https://join-lemmy.org/instances is here:

 * https://github.com/LemmyNet/joinlemmy-site/blob/main/src/shared/components/instances.tsx

Honestly, I'm not going to learn typescript to develop this feature, but if there's any typescript devs out there that are interested, your contributions would be much appreciated <3

**Comment by maltfield** [comment]
Tonight I hacked-up a quick `awesome-lemmy-instances` repo on GitHub that uses `lemmy-stats-crawler` and python to create this table that compares lemmy instances

 * https://github.com/maltfield/awesome-lemmy-instances

**Comment by maltfield** [comment]
I think the next most important item to add to this table is uptime.

Is there already somewhere that's tracking uptime of lemmy instances? Or is this something that I'd have to implement myself.

Obviously it's non-trivial to write my own lemmy instance uptime monitoring service, so I'd prefer to query that data from another source, if available.

**Comment by Nutomic** [comment]
Im not aware of such a service. You probably have to run crawls at regular intervals, and calculate what percentage was successful.

**Comment by maltfield** [comment]
TIL there's another table comparing lemmy instances already up, but it show the same data as mine (upvotes, fed, NC, and adult are missing)

 * https://the-federation.info/platform/73

**Comment by dessalines** [comment]
The fediverse observer one is my fav! I was gonna link it an hour ago but it was down lol, so I thought that would look bad.
