### ISSUE TITLE
Remove Bakchodi.org from listing

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/joinlemmy-site#165]
Similar to how wolfballs.com is not visible on the list, bakchodi.org should also be hidden or removed.

As far as I can tell they are a right-wing Hinduvta run instance, see comment here for example:

https://lemmy.serverfail.party/post/1142

Also mentioned in this  research paper on right-wing extremists: https://www.jstor.org/stable/48676736?seq=1

They originate from the banned subreddit /r/chodi  with reasons for their ban summarized on [wikipedia](https://en.wikipedia.org/wiki/Controversial_Reddit_communities).

**Comment by Nutomic** [comment]
wolfballs.com was always on the instance list, its not visible anymore because it was taken down. In general I dont like to remove any instances from the list for political reasons. These right-wing users you are talking about will still try to join Lemmy, and will join general purpose instances where they would have to be banned manually. Its much easier if they join explicit right-wing instances, then you just need to add those few instances to your blocklist and wont see anything from them.

Also Lemmy is for everyone, I dont see any good reason to exclude people from the platform for ideological reasons. There are already plenty of moderation tools which allow individual instances to block content which they dont want to see.

**Comment by poVoq** [comment]
Yeah I noticed recently that wolfballs.com was down. Permanently I hope?

While I sort of agree that if right-wingers want to use Lemmy they should be able to do so, it is a big difference to promote their instances on the main landing page people get directed to all the time.

Is there at least a plan to add some filtering like [Pixelfed](https://pixelfed.org/servers) does into regional or thematic instances, so that mostly only people interested in Indian instances will see them and hopefully be aware of what a cess-pool that is?

**Comment by dessalines** [comment]
I personally would rather not use join-lemmy.org to promote or link those instances in any way. They can have their own onboarding sites. I'd rather the bigots stay on centralized platforms, than join the fediverse and make our lives miserable there and increase our moderation workload.

**Comment by rootkea** [comment]
I'm an Indian Hindu (a secular one) and it absolutely disgusts me to see bakchodi.org linked on join-lemmy.org

@dessalines 
> I don't know anything about this instance in particular to feel comfortable making a decision about it.

bakchodi.org instance is a home of most vilest Indian racists fascists who are mostly refugee of r/chodi (who in turn are refugee from r/bakchodi  cause of mod drama. Not really in mood to explain in detail)
![r-chodi](https://github.com/LemmyNet/joinlemmy-site/assets/2694559/410e5f83-d2f8-4f37-a80b-0e6d45d03c25)

More about r/chodi: https://time.com/6160519/reddit-international-hate-speech-ban

@Nutomic 
> In general I dont like to remove any instances from the list for political reasons.
> I dont see any good reason to exclude people from the platform for ideological reasons.

Is being anti-Semitic openly and rejoicing thrashing Jews a mere a "different political position"?
![anti-semitic](https://github.com/LemmyNet/joinlemmy-site/assets/2694559/71a6843b-b931-42c2-84ab-43424d2b75fd)
Archive: https://web.archive.org/web/20230613142511/https://bakchodi.org/post/19583

Is admin and the site users eulogizing a massacre of 100+ people merely a "difference of ideology"?
Context:  116 people (men, women and children) were killed. Cauliflowers were planted to hide the buries bodies in fields. Search "Cauliflower farmer meme"

Also see:
1. https://en.wikipedia.org/wiki/1989_Bhagalpur_violence#Logain_massacre
2. https://www.reuters.com/article/idINIndia-30362020070618

**Comment by rootkea** [comment]
I'm an Indian Hindu (a secular one) and it absolutely disgusts me to see bakchodi.org linked on join-lemmy.org

@dessalines 
> I don't know anything about this instance in particular to feel comfortable making a decision about it.

bakchodi.org instance is a home of most vilest Indian racists fascists who are mostly refugee of r/chodi (who in turn are refugee from r/bakchodi cause of mod drama. Not really in mood to explain that drama in detail).
![r-chodi](https://github.com/LemmyNet/joinlemmy-site/assets/2694559/410e5f83-d2f8-4f37-a80b-0e6d45d03c25)

More about r/chodi: https://time.com/6160519/reddit-international-hate-speech-ban

@Nutomic 
> In general I dont like to remove any instances from the list for political reasons.
> I dont see any good reason to exclude people from the platform for ideological reasons.

Is being anti-Semitic openly and rejoicing thrashing Jews a mere a "different political position"?
![anti-semitic](https://github.com/LemmyNet/joinlemmy-site/assets/2694559/71a6843b-b931-42c2-84ab-43424d2b75fd)
Archive: https://web.archive.org/web/20230613142511/https://bakchodi.org/post/19583

Is admins and the site users eulogizing a massacre of 100+ people and hoping to have it repeated in 2029 under the guidance of a militant monk CM, merely a "difference of ideology"?
![cauliflower](https://github.com/LemmyNet/joinlemmy-site/assets/2694559/544755f3-efad-4d3b-9f83-4f7eba6b3972)
Archive: https://web.archive.org/web/20230613161018/https://bakchodi.org/post/2820

Context:  116 people (men, women and children) were killed during Logain massacre and cauliflowers were planted to hide the buried bodies in fields. Search "Cauliflower farmer meme". (And Yogi is a Hindu militant monk who has been made chief minister of the state by Modi. See: https://www.jgnt.co/yogi-adityanath-the-militant-monk)

Also see:
1. https://en.wikipedia.org/wiki/1989_Bhagalpur_violence#Logain_massacre
2. https://www.reuters.com/article/idINIndia-30362020070618

I don't care what sh\*thole these sc\*mbags reside in on the Internet but why is join-lemmy.org promoting that sh\*thole? Why are we giving them the visibility by linking/listing them?

**Comment by Nutomic** [comment]
@rootkea I have no connection with India and was not aware of this context. Your explanation sounds reasonable though. Can you make a pull request to add it to the [exclude list](https://github.com/LemmyNet/joinlemmy-site/blob/main/recommended-instances.json)?

**Comment by poVoq** [comment]
https://github.com/LemmyNet/joinlemmy-site/pull/183
