### ISSUE TITLE
Suggestion: Add a Quick User Guide to Lemmy

### ISSUE THREAD

**Issue by arsg0etia** [LemmyNet/joinlemmy-site#167]
Hello Lemmy team,

I would like to suggest adding a quick user guide that is placed on the header of https://join-lemmy.org/ or Lemmy instances. This guide can feature a short introduction to Lemmy and the Fediverse, and can be an optional feature for other instances.

Having a quick user guide would be helpful for new users who are not familiar with Lemmy or the Fediverse. It would provide them with an overview of what Lemmy is and how it works, making it easier for them to get started.

Thank you for considering my suggestion.

**Comment by dessalines** [comment]
This is in the docs repo https://join-lemmy.org/docs/users/01-getting-started.html
