### ISSUE TITLE
Remove burggit.moe and lemmy.burger.rodeo from listing

### ISSUE THREAD

**Issue by lionirdeadman** [LemmyNet/joinlemmy-site#180]
They advertise (and post) pornographic imagery involving children

**Comment by Nutomic** [comment]
I dont see anything like that on the frontpage. Also the sidebar says this:

> - No illegal content under Netherlands law
> - No content involving junior idols, child models, or anyone under the age of 18 in revealing clothing, questionable poses, or questionable situations

So if you see anything illegal, contact with the instance admin or with the hosting provider.

**Comment by rootkea** [comment]
Completed in https://github.com/LemmyNet/joinlemmy-site/pull/181
