### ISSUE TITLE
Copy instances to clipboard

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/joinlemmy-site#185]
I would like to copy the instances to the clipboard with a single click, enabling me to use them in a script without the need to copy/paste them individually.

**Comment by Nutomic** [comment]
You can run the crawler directly and parse the json output.

https://github.com/LemmyNet/lemmy-stats-crawler

**Comment by JediMaster25** [comment]
This is good enough.

To create the `stats.json` file, you can follow these steps:

1. Clone the `lemmy-stats-crawler` repository from GitHub by running the following command in your terminal:
```bash
git clone https://github.com/LemmyNet/lemmy-stats-crawler
```

2. Change your current directory to the cloned repository:
```bash
cd lemmy-stats-crawler
```

3. Build and run the crawler using Cargo:
```bash
cargo run -- --json > stats.json
```

This command will execute the `cargo run` command and redirect the output to a file named `stats.json`. The `--json` flag instructs the crawler to output the JSON data.

To create a script that extracts a list of instances from a JSON file and prints the resulting list, you can follow these instructions:

1. Import the `json` module to work with JSON data.
2. Read the JSON file and load the data into a Python object.
3. Extract the list of instances from the Python object.
4. Print the list of instances.

Here's the updated Python script:

```python
import json

# Read the JSON file and load the data into a Python object
with open("stats.json", "r") as file:
    data = json.load(file)

# Extract the list of instances from the Python object
instances = [instance["domain"] for instance in data["instance_details"]]

# Print the list of instances
print(instances)
```

When you run this script, it will read the JSON file, extract the list of instances from the loaded data, and then print the resulting list of instances.

To modify the script and extract only the instances with open registration from the JSON file, you can follow these updated instructions:

1. Import the `json` module to work with JSON data.
2. Read the JSON file and load the data into a Python object.
3. Create an empty list to store the instances with open registration.
4. Iterate over the list of instance details.
5. Check if the registration mode of the current instance is set to "open".
6. If the registration mode is "open", append the domain of the instance to the list of open instances.
7. Print the list of open instances.

Here's the updated Python script:

```python
import json

# Read the JSON file and load the data into a Python object
with open("stats.json", "r") as file:
    data = json.load(file)

# Create an empty list to store the instances with open registration
open_instances = []

# Iterate over the list of instance details
for instance in data["instance_details"]:
    # Check if the registration mode of the current instance is "open"
    if instance["site_info"]["site_view"]["local_site"]["registration_mode"] == "open":
        # If the registration mode is "open", append the domain of the instance to the list of open instances
        open_instances.append(instance["domain"])

# Print the list of open instances
print("Open instances:", open_instances)
```

When you run this updated script, it will read the JSON file, iterate over the instance details, and check if each instance has an open registration mode. It will then create a list of instances with open registration and print the resulting list.
