### ISSUE TITLE
Layout shift and slow font loading caused by errors related to `CaviarDreams` font

### ISSUE THREAD

**Issue by kacperwyczawski** [LemmyNet/joinlemmy-site#189]
# Screenshot of errors

![bug](https://github.com/LemmyNet/joinlemmy-site/assets/97523625/dc2d0320-cd93-4502-9abe-92edc2bef878)

# Steps to Reproduce

1. Open [`https://join-lemmy.org/`](https://join-lemmy.org/)
2. You will see errors in console and layout shift caused by slow loading of font.

# Technical details

- Browser: Firefox 114.0 (updating to 114.0.1 didn't change anything)

**Comment by dessalines** [comment]
I've removed this in the tailwind rework.
