### ISSUE TITLE
Remove the "Live Updates" section of the home page pending WS removal

### ISSUE THREAD

**Issue by academician** [LemmyNet/joinlemmy-site#196]
My understanding is that Lemmy 0.18 will remove the "Live updates" feature with the removal of websockets, so [that section](https://github.com/LemmyNet/joinlemmy-site/blob/7aef53b90061d6b0b0aa81d5ca25a4f65ac7f5e4/src/shared/components/main.tsx#L160) should probably just be removed.

**Comment by dessalines** [comment]
This is done in the rework. Thx
