### ISSUE TITLE
Adding list of Android apps to Join-Lemmy

### ISSUE THREAD

**Issue by lemmygod** [LemmyNet/joinlemmy-site#197]
Reference post: https://sh.itjust.works/post/312073

Up to date table of apps that were added originally to the post or afterwards from user input:

Total count so far: 12 (including Jerboa)

| Name              | Platform                     | OS          | Stage                                           | Link                                                                                     |
|-------------------|------------------------------|-------------|-------------------------------------------------|------------------------------------------------------------------------------------------|
| Artemis (Kmoon)   | Kbin, Lemmy (Upcoming)       | Android, iOS | Private Beta (Starts End of June)               | [/c/ArtemisApp@kbin.social](/c/ArtemisApp@kbin.social)                                    |
| Memmy             | Lemmy                        | Android, iOS | Android Release (Pending Play Store Approval)  | [/c/memmy@lemmy.ml](/c/memmy@lemmy.ml)                                                    |
| Mlem              | Lemmy                        | iOS         | Submitted for App Store Review (July 1)         | [/c/mlemapp@lemmy.ml](/c/mlemapp@lemmy.ml)                                                |
| Morpha            | Lemmy                        | Android, iOS | Under Development                              | [/c/morpha@vlemmy.net](/c/morpha@vlemmy.net)                                              |
| Thunder (FOSS)    | Lemmy                        | Android, iOS | Alpha Release                                   | [Thunder on GitHub](https://github.com/hjiangsu/thunder/releases/tag/v0.2.0-alpha) [Thunder Community](/c/thunder_app@lemmy.world)         |
| Beyond            | Lemmy                        | Android, iOS | Under Development                              | [Beyond on Lemmy](https://beehaw.org/post/647773)                                         |
| Jerboa            | Lemmy                        | Android     | Released                                        | [Jerboa on GitHub](https://github.com/dessalines/jerboa)                                 |
| Slide             | Lemmy                        | Android     | Under Development (More information coming)    | [Slide on Lemmy](https://lemmy.world/post/379068)                                         |
| Sync              | Lemmy                        | Android     | Research                                        | [/c/syncforlemmy@lemmy.world](/c/syncforlemmy@lemmy.world)                                |
| Liftoff (FOSS)  | Lemmy                        | Android     | Under Development                              | [Community](/c/liftoff@lemmy.world),                                           [GitHub](https://github.com/liftoff-app), [TestFlight](https://testflight.apple.com/join/e6ZEbxuR), [APK Release on GH](https://github.com/liftoff-app/liftoff/releases/tag/v0.9.11)|
| Connect           | Lemmy                        | Android     | Beta                                            | [Connect Release Post](https://beehaw.org/post/698247), [Connect Community](https://lemmy.ca/c/lemmyconnect)                                  |
| Lemon             | Lemmy                        | iOS         | Development, Beta in Early July                 | [Lemon Introduction](https://lemm.ee/post/127800), [Lemon Community](https://lemm.ee/c/lemon) |
| Summit            | Lemmy                        | Android     | Released                                        | [Summit on Google Play](https://play.google.com/store/apps/details?id=com.idunnololz.summit), [Summit Demo Video](https://youtube.com/shorts/MMpMHwzTuII) |
| WefWef | Lemmy | Web App / PWA | Released | [Community](https://lemmy.world/c/wefwef), [Web App](https://wefwef.app/posts/lemmy.world/all) |

**Comment by SonGokuSSJ** [comment]
Via google I found another app: Remmel:

https://github.com/uuttff8/Remmel

Still in the works though (all appstore links not working, as not ready yet).

**Comment by lemmygod** [comment]
No updates in 4 months for Remmel. I'd suggest waiting for dev to restart because, according to comments in search results, people used it before but now it's not compatible with current Lemmy.

I removed Limbo & Lemmynade & added Liftoff with new links for source, app & community.

**Comment by SonGokuSSJ** [comment]
OK, only saw, that Remmel was there and he mentioned, that you need to install it via sideload (or something like that). 

If I am not wrong, Liftoff will be for both iOS and Android (I have it installed on iOS, so I am sure it works there) and you even added the Testflight link).

**Comment by lemmygod** [comment]
There is nothing on that list that is't in my table except for WefWef which is an alternative frontend, not an app, and "Unnamed", which is not even started and has no tracking afaik so I didn't feel the need to add it. I'll add WefWef cuz 🤷

**Comment by CTalvio** [comment]
[Thunder](https://github.com/thunder-app/thunder) has picked up several contributors (myself included) and now has a play store release.

**Comment by CTalvio** [comment]
Thunder now has a play store release.

**Comment by wiki-me** [comment]
Better to add [awesome-lemmy](https://github.com/dbeley/awesome-lemmy) , it's what is linked to in the [read me](https://github.com/LemmyNet/lemmy/blob/main/README.md). (plus you can submit issues and pull requests)

**Comment by dessalines** [comment]
I added nearly all these to the `tailwind` site rebuild now. Any new ones, ppl can add via PRs.
