### ISSUE TITLE
Updated info for Mlem for Lemmy on https://join-lemmy.org/apps

### ISSUE THREAD

**Issue by BrooklynMan** [LemmyNet/joinlemmy-site#200]
Hello!

on the https://join-lemmy.org/apps site, the app is now called

Mlem for Lemmy

the new icon is linked at the bottom of this post. the new TestFlight link is:

https://testflight.apple.com/join/MelFP11Y

and the link to our re-located repo is:

https://github.com/mormaer/Mlem

Thank you so much for updating this info!

Cheers!

![melmapp icon](https://github.com/LemmyNet/joinlemmy-site/assets/5836168/491ec012-8980-45af-bae0-295588f925c7)

**Comment by WestonHanners** [comment]
we've moved github to an ORG, please use this github link.

https://github.com/mlemgroup/mlem
