### ISSUE TITLE
Loli-friendly instance should be removed from join-lemmy.org/instances

### ISSUE THREAD

**Issue by aranym1** [LemmyNet/joinlemmy-site#203]
lemmy.burger.rodeo specifically notes itself as "Loli/Shota/Cub friendly!" in their onsite description.. It should probably be removed.

With the influx from Reddit, this page will be a lot of people's first impression of the platform.
I get they have a right to have their own space, but this is not an appropriate place to mention it.
This casts a very bad light over the rest of us, the far majority of users who don't access that kind of content.

I'm free for discussion if anybody disagrees.

**Comment by sunaurus** [comment]
It has been excluded for a while: 

https://github.com/LemmyNet/joinlemmy-site/blob/main/recommended-instances.json#L29

Not sure why it's visible on join-lemmy.org, seems something is broken

**Comment by lionirdeadman** [comment]
Yeah, further proof that things are broken - Beehaw.org is back on top of the recommended list and lemmy.world or lemm.ee are gone. It seems it rollbacked to some old version.

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/joinlemmy-site/pull/206
