### ISSUE TITLE
Add QR codes for crypto donation addresses

### ISSUE THREAD

**Issue by erciccione** [LemmyNet/joinlemmy-site#219]
QR codes will make much easier for visitors to donate cryptocurrencies. Currently the only way is to copy-paste the address, which is quite inconvenient, especially on mobile: https://join-lemmy.org/donate

**Comment by dessalines** [comment]
I checked on this, and some of those cryptos don't have URL link formats. If you know them tho, I'll re-open and could add these.

**Comment by erciccione** [comment]
The URL format is not needed to generate a qr code pointing to the address. I went ahead and already generated the qr pointing to Lemmy's donation address for the cryptocurrencies you list. Please double check that each qr code points to the right address.

### Monero

![monero](https://github.com/LemmyNet/joinlemmy-site/assets/28106476/6177a014-99b7-4803-b486-2e685bdec063)


### Bitcoin

![btc](https://github.com/LemmyNet/joinlemmy-site/assets/28106476/918aef14-15bb-4ec7-b3b7-de6d2b4ef98b)

### Cardano

![cardano](https://github.com/LemmyNet/joinlemmy-site/assets/28106476/b421a044-f3b9-4eca-955f-cee9dba7c780)

### Eth

![eth](https://github.com/LemmyNet/joinlemmy-site/assets/28106476/6f16fe35-dcb1-43af-850b-3dcb0d3ddf7d)

**Comment by dessalines** [comment]
I'm not going to include images, I would generate these. If all you did was take the strings, that's not very useful to apps. They need url strings.

**Comment by erciccione** [comment]
@dessalines You don't need url strings to create a qr code for crypto payments, only an address. These qr codes where generated using https://www.coinster.tools/qr-code-generator. I already tested the bitcoin and monero qr codes posted above and confirm they work, you can test them easily by using a mobile wallet, scanning the image and confirming the address in the qr matches your donation address.

You can definitely generate them in code with some library, but i'm not sure if it works the effort, when you need only 4 images and generating them is very easy. There is [this python library for example](https://pypi.org/project/crypto-qr-codes/) (and as you can see only an address is needed).

I should probably point out that i've been working exclusively on Monero and other cryptocurrencies for the past >6 years, so i have familiarity with the technology and i'll be happy to work together the best way to facilitate donations to lemmy :)

**Comment by dessalines** [comment]
If all it is, is a string with the address, that's really easy.
