### ISSUE TITLE
[Bug] Some instances no longer appear in the list despite being online and meeting requirements

### ISSUE THREAD

**Issue by delendum** [LemmyNet/joinlemmy-site#228]
I've noticed that my instance is only intermittently present on the join-lemmy.org instance list. I really have no idea why this is happening, so I hope you may be able to have a look through the crawler logs to see if there's anything strange going on (or is there something in the way the page is generated?)

What I can say is this isn't driven by the instance going down, and I can see the crawler touching base at regular intervals even when the site isn't on the list (I'm guessing "lemmy-stats-crawler" is it?)

I know this is a minor thing, but it's the only way that people can discover this instance and it's a shame for it to not be there.

Instances confirmed to be missing:
- https://lemdit.com
- https://lemmy.nz
- https://beehaw.org

Edit: Updated title for better accuracy.

**Comment by delendum** [comment]
https://lemmy.nz is also missing from the list, I'm guessing there are probably others that we don't know about.

The crawler is definitely touching base:

65.21.61.25 - - [28/Jul/2023:04:00:48 +1200] "GET /nodeinfo/2.0.json HTTP/1.1" 200 221 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:04:00:48 +1200] "GET /nodeinfo/2.0.json HTTP/1.1" 200 221 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:04:00:48 +1200] "GET /api/v3/site HTTP/1.1" 200 12641 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:04:00:48 +1200] "GET /api/v3/site HTTP/1.1" 200 12641 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:04:00:48 +1200] "GET /api/v3/federated_instances HTTP/1.1" 200 340859 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:04:00:48 +1200] "GET /api/v3/federated_instances HTTP/1.1" 200 340859 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:05:00:47 +1200] "GET /nodeinfo/2.0.json HTTP/1.1" 200 221 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:05:00:47 +1200] "GET /nodeinfo/2.0.json HTTP/1.1" 200 221 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:05:00:47 +1200] "GET /api/v3/site HTTP/1.1" 200 12641 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:05:00:47 +1200] "GET /api/v3/site HTTP/1.1" 200 12641 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:05:00:47 +1200] "GET /api/v3/federated_instances HTTP/1.1" 200 340985 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:05:00:47 +1200] "GET /api/v3/federated_instances HTTP/1.1" 200 340985 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:06:00:40 +1200] "GET /nodeinfo/2.0.json HTTP/1.1" 200 221 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:06:00:40 +1200] "GET /nodeinfo/2.0.json HTTP/1.1" 200 221 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:06:00:40 +1200] "GET /api/v3/site HTTP/1.1" 200 12641 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:06:00:40 +1200] "GET /api/v3/site HTTP/1.1" 200 12641 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:06:00:40 +1200] "GET /api/v3/federated_instances HTTP/1.1" 200 341101 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:06:00:40 +1200] "GET /api/v3/federated_instances HTTP/1.1" 200 341101 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:07:00:49 +1200] "GET /nodeinfo/2.0.json HTTP/1.1" 200 221 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:07:00:49 +1200] "GET /nodeinfo/2.0.json HTTP/1.1" 200 221 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:07:00:49 +1200] "GET /api/v3/site HTTP/1.1" 200 12641 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:07:00:49 +1200] "GET /api/v3/site HTTP/1.1" 200 12641 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:07:00:49 +1200] "GET /api/v3/federated_instances HTTP/1.1" 200 341101 "-" "lemmy-stats-crawler"
65.21.61.25 - - [28/Jul/2023:07:00:49 +1200] "GET /api/v3/federated_instances HTTP/1.1" 200 341101 "-" "lemmy-stats-crawler"

**Comment by lionirdeadman** [comment]
beehaw.org is there now and it's been there for a while, it's likely it happened to be down at the same time as a scan.

**Comment by delendum** [comment]
All instances are back on there now including mine, significantly more than when this was reported. I think intermittently there's something funky going on with the front page generation.
