### ISSUE TITLE
Add Lunar for Lemmy to the site

### ISSUE THREAD

**Issue by mani-sh-reddy** [LemmyNet/joinlemmy-site#236]
Hi, I would love to add my app [Lunar](https://github.com/mani-sh-reddy/Lunar) to https://join-lemmy.org/apps

It's a native iOS app written in Swift and SwiftUI (currently also has very basic Kbin support)

https://github.com/mani-sh-reddy/Lunar

**Comment by dessalines** [comment]
In the future, make sure your commit or PR has the word `fixes #ISSUE_NUM`
