### ISSUE TITLE
Automatically update donation stats

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/joinlemmy-site#248]
https://github.com/LemmyNet/joinlemmy-site/pull/243 adds a total donations amount. This amount is currently [hardcoded](https://github.com/LemmyNet/joinlemmy-site/pull/243/files#diff-0aaa21c0becdc68ee532e9458778579dd5bfd1c1173fe0091aaef1bb3a7cf3dfR117-R129) and needs to be updated manually. It would be very nice if we could pull the numbers from each site at build time so it stays up to date. The site is already rebuilt automatically every hour (to update the instance list), so donation amounts can be updated in the same way.

Liberapay: `https://liberapay.com/Lemmy/public.json` ([usage](https://github.com/badges/shields/blob/master/services/liberapay/liberapay-base.js))
Open Collective: `https://opencollective.com/lemmy.json` ([docs](https://docs.opencollective.com/help/contributing/development/api/collectives))
Patreon: `curl https://www.patreon.com/api/campaigns/2692831` ([found here](https://github.com/AceAsin/PatreonBadge))

**Comment by dessalines** [comment]
Ah thanks, in that case I'll start working on a little script and create a repo that I can add as a submodule.
