### ISSUE TITLE
join-lemmy.org/instances takes up 2-5GB of memory in Safari; crashes tab on iPhone

### ISSUE THREAD

**Issue by aeharding** [LemmyNet/joinlemmy-site#261]
I am experiencing problems with new new website page of https://join-lemmy.org/instances crashing on my iPhone 13. When I load on Safari on my desktop machine, it loads, but consumes a very large amount of memory. It spikes to 5GB on page load, and settles to around 2.5GB.

<img width="652" alt="Screenshot 2023-11-01 at 10 54 58 AM" src="https://github.com/LemmyNet/joinlemmy-site/assets/2166114/156a92a6-c08b-48de-a6fd-f3354a203776">
<img width="877" alt="Screenshot 2023-11-01 at 10 54 27 AM" src="https://github.com/LemmyNet/joinlemmy-site/assets/2166114/1fe86ca5-e7b2-4f61-8767-465b6f8f965d">

**Comment by dessalines** [comment]
This is gonna be a tough one, because I don't have an iOS device, so I'd need someone to help with it. 

I tested this page out on various android browsers, as well as desktop firefox and chromium, all stay under ~ 100 MB, even with all the instances loaded.

**Comment by dessalines** [comment]
Good call, i'll start on that shortly.

**Comment by aeharding** [comment]
Just pulled it down locally; running perfect. Thanks @dessalines!

**Comment by dessalines** [comment]
No probs, thx for pointing this out!
