### ISSUE TITLE
Add "innovating without patents" badge

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/joinlemmy-site#283]
```
<a href="https://endsoftwarepatents.org/innovating-without-patents"><img style="height: 120px;" src="https://static.fsf.org/nosvn/esp/logos/innovating-without-patents.svg"></a>
```

https://endsoftwarepatents.org/innovating-without-patents/

**Comment by dessalines** [comment]
You mean on the readme?

**Comment by dullbananas** [comment]
It should also be on join-lemmy

**Comment by dessalines** [comment]
We don't have any badges / promotional type stuff on the site, but I'll add this to lemmy's readme, which is where those should go.
