### ISSUE TITLE
Invalid context.json

### ISSUE THREAD

**Issue by zoggy** [LemmyNet/joinlemmy-site#292]
Hello,

it seems that the `context.json` file we can find for example at https://join-lemmy.org/context.json is invalid. It should contain a `@context` entry, as stated [here](https://www.w3.org/TR/json-ld11-api/#overview):

« If [context](https://www.w3.org/TR/json-ld11/#dfn-context) is a [string](https://infra.spec.whatwg.org/#javascript-string), it represents a reference to a remote [context](https://www.w3.org/TR/json-ld11/#dfn-context). We dereference the remote context and replace context with the value of the @context [entry](https://infra.spec.whatwg.org/#map-entry) of the top-level object in the retrieved JSON-LD document. If there's no such [entry](https://infra.spec.whatwg.org/#map-entry), an [invalid remote context](https://www.w3.org/TR/json-ld11-api/#dom-jsonlderrorcode-invalid-remote-context) has been detected. Otherwise, we process [context](https://www.w3.org/TR/json-ld11/#dfn-context) by recursively using this algorithm ensuring that there is no cyclical reference.»

**Comment by zoggy** [comment]
It may be this file: src/assets/lemmy_federation_context.json

**Comment by Nutomic** [comment]
Yes its that file. Can you make a pull request with the fix? Im not familiar with the correct format as Lemmy doesnt parse the context at all.

**Comment by dessalines** [comment]
Fixed by that above PR.
