### ISSUE TITLE
Separate Web frontends that are site specific and the ones that are general

### ISSUE THREAD

**Issue by blacklightpy** [LemmyNet/joinlemmy-site#329]
Frontends like Alexanderite, Photon and Voyager let you sign in to any instance from within themselves, but Lemmy UI, mlmym, lemmyBB, etc. are only available per site.

The general frontends are better for a person to bookmark and visit, because they let you easily interact with posts, without having to copy the current URL, switch to home instance and paste it into the search bar.

**Comment by dessalines** [comment]
This is just a feature of *some* web UIs, but they're all still web UIs. I don't see any reason to separate them just because of that feature, and I don't even know what you'd call it anyway.

**Comment by blacklightpy** [comment]
That's exactly what I said about separating them. They are instance-specific frontends vs generic frontends. You could link to both the official hosted instance of the generic frontends and their source code, while you could just link to the source code for the instance-specific frontends.

The importance is that when you use them, Lemmy is a single network, while if you use a specific instance, you won't have a login session in that instance.

**Comment by blacklightpy** [comment]
By that approach, the generic frontends will remain just called Web apps, while the instance-specific frontends will be called Web UIs.

Web UI - Instance-Specific Frontend
Web App - Generic Lemmy Client

**Comment by dessalines** [comment]
> while you could just link to the source code for the instance-specific frontends.

This is exactly what we do for all lemmy apps, only link their source code.

> You could also put the generic frontends in the Web apps section, and move the instance-specific frontends to a separate page. Because only generic frontends fit in with apps on other platforms, while an instance-specific frontend is not an "app" per se, and is more like a site-specific theme.

This is way too complicated for a simple dropdown filter on the apps page. We only link the source code for them anyway, we definitely shouldn't be linking specific sites for them, that could be dozens. This distinction is a lot less clear than you're making it out to be: there are client-side SPAs, SSRs, isomorphic apps, and plenty of other variations that all count as web apps.

**Comment by blacklightpy** [comment]
> This is way too complicated for a simple dropdown filter on the apps page.

I'm saying that Web UIs won't fit into the apps section. I don't see any point in separating SPAs, SSRs, PWAs, etc.

Lemmy-UI, lemmyBB and mlmym aren't apps, you can't use them to sign into any instance.

But Voyager, Alexanderite and Photon let you sign in to any instance. This is the same as other clients.

They are both on web, that's common. But a Lemmy instance won't host Voyager, Alexanderite or Photon (in the sense of it being the instance-specific UI) because they can switch instances. They'd only host Lemmy-UI, lemmyBB or mlmym.

They'd only host Voyager, Alexanderite or Photon as part of hosting a generic frontend. They may like it for its UI, but it still is a generic web app rather than instance-specific.

---

![image](https://github.com/LemmyNet/joinlemmy-site/assets/28739146/47b638d9-e4e3-4096-a4f1-c7f774411a4f)

I'd say Web UIs fit somewhere like here rather than among apps, because apps are intended to be user-oriented, while Web UIs are developer oriented.
