### ISSUE TITLE
Portuguese and Portuguese (Brazil)

### ISSUE THREAD

**Issue by paulo-roger** [LemmyNet/joinlemmy-site#407]
Most ActivityPub platforms I have used does not differentiate both, what is IMO right. Both are the same language and often we interact with people from both countries.

My request is to remove Portuguese Brazil from the site and leave only Portuguese, because this might lead to confusion.

When a new potential user access join-lemmy they will see:

![image](https://github.com/user-attachments/assets/ab28b099-abee-4a72-96e6-b654a1795eb9)

If we are lucky and they click `Portuguese`  both communities show up

![image](https://github.com/user-attachments/assets/07b2bfad-2be3-44bc-adf5-d19e137901cf)

otherwise:

![image](https://github.com/user-attachments/assets/e2120e97-b7ee-42c6-82b2-dfb60c90a2b0)

Making them believe there is not a Brazilian instance.

**Comment by dessalines** [comment]
I think its best to keep both, since there are separate translation strings. But I'll add pt_br to all the pt instances in the instance list rn, to not encounter this problem.

**Comment by paulo-roger** [comment]
Thanks!
