### ISSUE TITLE
Navbar dropdown broken.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/joinlemmy-site#431]
Probably a dep update that caused this.

**Comment by Nutomic** [comment]
So the dependency bot is not only annoying but actively breaks our projects? It really does more harm than good. My suggestion is to revert package.json and lockfile to the last version before enabling the bot (https://github.com/LemmyNet/joinlemmy-site/tree/d52c6cf29dee59c53f3fcb5d0536801098243105), and also disable dependabot (or if you insist, only enable it for [security updates](https://docs.renovatebot.com/presets-security/#securityonly-security-updates).
