### ISSUE TITLE
Donation Page 404

### ISSUE THREAD

**Issue by TalkinWhip** [LemmyNet/joinlemmy-site#45]
When clicking on the beer glass, it takes you to a not-found page at https://join.lemmy.ml/sponsors

Edit: looking through the files - it should probably be https://join.lemmy.ml/support and is a lemmy issue instead of a joinlemmy-site one

**Comment by dessalines** [comment]
That's true, we deployed that joinlemmy early, but we're getting ready for another lemmy release this monday, so that link will be fixed then.

**Comment by dessalines** [comment]
This should be good now.
