### ISSUE TITLE
AsyncAPI definition improvements suggestion

### ISSUE THREAD

**Issue by derberg** [LemmyNet/joinlemmy-site#48]
Hi folks. I'm one of maintainers at AsyncAPI.
I promised some time ago to @gazconroy that I will try to find time to look at your AsyncAPI doc and suggest some improvements.

So here I am 😄 I recently produced a lot of content around WebSocket API. Some articles and videos and example so my knowledge in the topic is super refreshed and can jump it.

Let me know if you are interested and how to approach it.

☮️

**Comment by gazconroy** [comment]
Thank you, Lukasz.

From a (my) technical writer's point of view:
- Does the specification use the features of the AsyncAPI standard as well as it could?
- Is it missing any 'tricks'? Anything that has developed in AsyncAPI recently: for instance, 'bindings' might be a solution to having to document the HTTP API within the Markdown

On the subject of new features, it would be great if the React web component could generate the tags (like Open API implementations such as Rec and Swagger UI) so that the lengthy list of 'endpoints' is categorised by the assigned tag.

**Comment by derberg** [comment]
@gazconroy

> On the subject of new features, it would be great if the React web component could generate the tags (like Open API implementations such as Rec and Swagger UI) so that the lengthy list of 'endpoints' is categorised by the assigned tag.

Not 100% sure how it works in tools mentioned by you but I think we support it already in HTMLl template https://github.com/asyncapi/html-template#supported-parameters and therefore also in the next major version that we work on for the react component -> https://github.com/asyncapi/asyncapi-react/releases/tag/v1.0.0-next.3 (now HTML template is powered by this release candidate)

> Does the specification use the features of the AsyncAPI standard as well as it could?

Spec is used a bit differently than it should:
- [server URL](https://github.com/LemmyNet/joinlemmy-site/blob/main/src/assets/scripts/asyncapi.yaml#L73) includes path that should actually be part of the channel name
- [channel](https://github.com/LemmyNet/joinlemmy-site/blob/main/src/assets/scripts/asyncapi.yaml#L94) names do not represent path. Looking at current docs, I assume lemmy's API has just one channel/endpoint/entrypoint and multiple different messages that can get in, so channel name should be `api/v2/ws` and you should use `oneOf` key at the message level
- I think you are using `publish/subscribe` on each channel to describe AsyncAPI missing feature to describe request/reply pattern. I definitely recommend introducing a kind of custom extension that misusing the spec. Look for example how I did this in this article https://www.asyncapi.com/blog/websocket-part2#describe-responses---specification-extensions
- `operationId` is not really needed if you do not use the file for code generation

> Is it missing any 'tricks'? Anything that has developed in AsyncAPI recently: for instance, 'bindings' might be a solution to having to document the HTTP API within the Markdown

the candidate for next react component now supports rendering in the UI the bindings and extensions

**Comment by gazconroy** [comment]
Thank you @derberg . I've updated the spec as suggested. Is the file at https://github.com/gazconroy/joinlemmy-site/tree/asyncapi/src/assets/scripts more in tune now?

It now _feels_ more logical to my mind, anyway

**Comment by derberg** [comment]
Oh yes, that looks way much better, well done 👏🏼 

I only suggest to use the extension that I for now recommend to mark what is the response to a given message. So in the `loginRequest` message you can do something like:

```
x-response:
      $ref: '#/components/messages/loginResponse'
```

This is how latest HTML template will display it:
![Screenshot 2021-06-02 at 13 20 21](https://user-images.githubusercontent.com/6995927/120471724-58b1ce80-c3a5-11eb-8fcb-8e12737557b6.png)

**Comment by gazconroy** [comment]
Cheers. Your help is much appreciated. 

Is [Playground](https://playground.asyncapi.io/) lagging behind the HTML template? It renders like this, there: 

![playground](https://user-images.githubusercontent.com/26181682/120494103-6cfcc800-c3b3-11eb-97fd-9294e183c4d2.png)

**Comment by derberg** [comment]
yeah, it is a bit behid, the only not yet automated part of asyncapi tools 😅 
you can check here https://asyncapi.github.io/asyncapi-react/ it is what powers html-template too

**Comment by gazconroy** [comment]
The HTML template is looking good these days, @derberg! Thank you for your suggestions, they really do improve the document.

**Comment by derberg** [comment]
@gazconroy happy I could help!
