### ISSUE TITLE
GitHub organization still points to join.lemmy.ml

### ISSUE THREAD

**Issue by remram44** [LemmyNet/joinlemmy-site#56]
Wasn't sure where to open an issue about your GitHub setup, this seems the most appropriate.

#52 changed the domain from join.lemmy.ml to join-lemmy.org but the GitHub org still points to the old domain:

![screenshot](https://user-images.githubusercontent.com/426784/123826980-3e004600-d8ce-11eb-9fd5-e439194b9362.png)

Cheers!

**Comment by dessalines** [comment]
Thanks! Got it.
