### ISSUE TITLE
Deploy site automatically

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/joinlemmy-site#65]
Now that we have our own drone.io server, we can use it to run builds based on [cron](https://docs.drone.io/cron/). So we could configure it to build joinlemmy once every day at a fixed time, and then setup a cronjob on our server to pull the updated image an hour later. This would mainly be useful to get rapid updates of new documentation, and updates of the instance list.

**Comment by dessalines** [comment]
You have this set up now.
