### ISSUE TITLE
join-lemmy.org website unreachable from IPv6-only ISPs

### ISSUE THREAD

**Issue by ptitgnu** [LemmyNet/joinlemmy-site#67]
Hi,

The website seems to be unreachable from networks that no longer have IPv4/legacyIP.
The AAAA record exists but the web server does not respond.
-> http://ipv6-test.com/validate.php?url=join-lemmy.org

I think it's just a small network config issue on the VPS. Can you fix it ?
Thanks :)

**Comment by Nutomic** [comment]
IPv6 is now available, in fact it was much easier than i thought.
