### ISSUE TITLE
[Feature] Add JS Licenses

### ISSUE THREAD

**Issue by ncorder** [LemmyNet/joinlemmy-site#68]
## Feature

LibreJS Compliant JavaScript Licenses

___________________________

**Comment by ncorder** [comment]
I have done some work with LibreJS in the past and wanted to ask some questions that might also help me make a PR to add licenses more properly.

The main script that seems to be flagged is the [/static/js/client.js](https://web.archive.org/web/20211029162045/https://join-lemmy.org/static/js/client.js) and is referenced in both `index.tsx` and `webpack.config.js` [[1](https://github.com/LemmyNet/joinlemmy-site/search?q=client.js)] files, not including linked/sumodule repositories.

What is the license file for this script? The static content states:

 `/*! For license information please see client.js.LICENSE.txt */`

_________________________________________

I am a bit new to your site, but it appears the template for the main website is [`components/main.tsx`](https://github.com/LemmyNet/joinlemmy-site/blob/0bdd08d018cf0725a0843a8dc99ab67dc7c5db6a/src/shared/components/main.tsx). 

I'd assume you could craft a `javascript` page and use the format for JS tables

```
<table id="jslicense-labels1">
    <tr>
        <td><a href="{url-to-license}">{license-name}</a></td>
        <td><a href="{location of file}">{file name}</a></td>
    </tr>
</table>
```

How are pages currently generated?

**Comment by ncorder** [comment]
The banner setup in `webpack.conf.js` includes a license:

`  @license magnet:?xt=urn:btih:0b31508aeb0634b347b8270c7bee4d411b5d4109&dn=agpl-3.0.txt AGPL v3.0`

but i do not see a `// @license-end`

_________________________

**Comment by dessalines** [comment]
The banner is located at : https://github.com/LemmyNet/joinlemmy-site/blob/main/webpack.config.js#L8

**Comment by dessalines** [comment]
Stale, but I can re-open if someone wants to work on this.
