### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by yujiri8** [LemmyNet/joinlemmy-site#71]
https://join-lemmy.org/docs/en/federation/lemmy_protocol.html links with the text "Federation Overview" to https://join-lemmy.org/docs/en/federation/contributing_federation_overview.html, which is a 404.

From the left sidebar, I think it's suppsoed to link to https://join-lemmy.org/docs/en/federation/overview.html.

**Comment by Nutomic** [comment]
Would you like to make a PR to fix it?
